/* Apollo — per-component implementation specs.
   Consumed by the Spec d'implémentation panel (right-click a component).
   Shape per id: { s: summary, p: ["name|values|(default)"], t: [tokens], st: [states], a: [a11y], do: [...], dn: [...] } */
window.APOLLO_SPECS = {
  /* ── ATOMS ── */
  'c-button': { s: "Primary action trigger. Verb labels; one primary per view.",
    p: ["variant|primary · secondary · outline · ghost · link|(primary)", "size|sm · md · lg|(md)", "icon|none · leading · trailing|(none)", "disabled · loading · fullWidth|boolean|(false)"],
    t: ["radius --ys-r-md · font --ys-fw-medium", "fill --ys-blue → hover --ys-blue-hover", "sm --ys-fs-11 · md/lg --ys-fs-13/14", "disabled bg --ys-border · fg --ys-muted"],
    st: ["default → hover (fill −1 step) → active", "focus-visible: 2px --ys-blue ring, 2px offset", "disabled: not-allowed, no hover", "loading: spinner replaces label, width held"],
    a: ["Real <button>; target ≥ 44×44 on mobile", "Icon-only needs aria-label", "loading sets aria-busy"],
    do: ["One primary action per view", "Verb labels (« Enregistrer »)", "Success fill only for confirm/validate"],
    dn: ["Success fill as a generic accent", "Two competing primaries side by side", "Disable without explaining why"] },
  'c-badge': { s: "Static status/label marker on a tinted surface.",
    p: ["tone|neutral · info · success · warning · danger|(neutral)", "variant|filled · subtle|(subtle)"],
    t: ["radius --ys-r-pill", "bg --ys-{tone}-bg · fg --ys-{tone}-fg", "font --ys-fs-11 / --ys-fw-semi"],
    st: ["Static (no interaction)"],
    a: ["Not a button — never attach click handlers", "Colour is reinforced by the label text, never colour-only"],
    do: ["Keep labels to one word", "Pair emoji status (✅⚠️🔵) inside the pill"],
    dn: ["Use as a button", "Put long text in a badge"] },
  'c-input': { s: "Single-line text field with label, helper and states.",
    p: ["type|text · email · password · number|(text)", "state|default · focus · error · disabled|(default)", "icon|none · leading · trailing|(none)", "helper · error|string"],
    t: ["radius --ys-r-md · border --ys-border", "focus border --ys-blue", "error border --ys-danger-fg · bg --ys-danger-bg", "text --ys-text · placeholder --ys-muted"],
    st: ["default → focus (border --ys-blue)", "error: red border + helper message", "disabled: --ys-bg fill, muted text"],
    a: ["Always a <label> bound by for/id", "Error text via aria-describedby + aria-invalid", "Target height ≥ 44px on mobile"],
    do: ["Show the error message, not just red", "Keep helper text persistent"],
    dn: ["Placeholder as the only label", "Colour-only error signalling"] },
  'c-choice': { s: "Checkbox & radio — multi vs single select.",
    p: ["type|checkbox · radio", "checked · disabled|boolean|(false)", "label|string"],
    t: ["radius checkbox --ys-r-xs · radio --ys-r-full", "checked bg --ys-blue", "border --ys-border-2"],
    st: ["unchecked → checked → indeterminate (checkbox)", "focus-visible ring --ys-blue", "disabled muted"],
    a: ["Native <input> + <label>", "Radio group shares one name", "Hit target ≥ 44px incl. label"],
    do: ["Checkbox for many, radio for one", "Click label toggles control"],
    dn: ["Radio for independent toggles", "Tiny click targets"] },
  'c-toggle': { s: "Instant on/off switch (no save needed).",
    p: ["checked · disabled|boolean|(false)", "label|string"],
    t: ["track on --ys-blue · off --ys-border-2", "knob --ys-white · radius --ys-r-full"],
    st: ["off → on (slide 150ms)", "focus-visible ring", "disabled muted"],
    a: ["role=switch + aria-checked", "Operable with Space/Enter"],
    do: ["Use for immediate settings", "Label the state clearly"],
    dn: ["Use where a Save step is required (use checkbox)", "Animate slower than 150ms"] },
  'c-select': { s: "Select dropdown & multi-line textarea.",
    p: ["control|select · textarea", "state|default · focus · error · disabled|(default)", "rows|number (textarea)"],
    t: ["radius --ys-r-md · border --ys-border", "focus border --ys-blue", "text --ys-fs-13"],
    st: ["default → focus → error → disabled", "textarea: vertical resize only"],
    a: ["Native <select> / <textarea> + label", "Error via aria-invalid"],
    do: ["Native select on mobile", "Cap textarea min-height"],
    dn: ["Custom dropdown without keyboard support", "Horizontal textarea resize"] },
  'c-phone': { s: "Phone input with country prefix.",
    p: ["country|ISO code|(FR)", "value|E.164 string"],
    t: ["radius --ys-r-md · border --ys-border", "prefix divider --ys-border"],
    st: ["default → focus → error", "invalid number: error border"],
    a: ["type=tel + inputmode=tel", "Label the field, announce country"],
    do: ["Default to FR (+33)", "Validate on blur"],
    dn: ["Block paste", "Force a format the user can't see"] },
  'c-tag': { s: "Interactive chip — filter or removable token.",
    p: ["variant|filled · outline|(filled)", "removable|boolean|(false)", "selected|boolean|(false)"],
    t: ["radius --ys-r-pill", "selected bg --ys-blue-mid · fg --ys-blue-fg", "border --ys-border"],
    st: ["default → hover → selected", "removable: × on hover/focus"],
    a: ["Filter tags are buttons/checkboxes", "Remove × has aria-label"],
    do: ["Use for filters and removable inputs", "Keep one word"],
    dn: ["Confuse with static Badge", "Hide the remove affordance"] },
  'c-avatar': { s: "Monogram or image identity chip.",
    p: ["size|sm · md · lg|(md)", "shape|circle|(circle)", "initials · src|string"],
    t: ["radius --ys-r-full", "bg --ys-blue-mid · fg --ys-blue-fg", "sizes 28/34/44px"],
    st: ["Static; optional presence dot"],
    a: ["alt text on images", "Monogram has aria-label of full name"],
    do: ["Fall back to initials", "Keep 2 letters max"],
    dn: ["Stretch non-square images", "Rely on colour to identify a person"] },
  'c-rating': { s: "Star rating, display or input.",
    p: ["value|0–5", "mode|display · input|(display)", "count|number"],
    t: ["star --ys-orange · empty --ys-border-2", "label --ys-muted"],
    st: ["input: hover preview → selected", "focus-visible per star"],
    a: ["Input is a radiogroup (1–5)", "Display has aria-label « 4,6 sur 5 »"],
    do: ["Show the numeric value + count", "Half-stars for averages"],
    dn: ["Colour-only (add the number)", "Tiny tap targets in input mode"] },
  'c-tooltip': { s: "Short hover/focus hint on an element.",
    p: ["placement|top · right · bottom · left|(top)", "text|string"],
    t: ["bg --ys-text · fg --ys-white", "radius --ys-r-sm · --ys-fs-11"],
    st: ["show on hover + focus (≈120ms delay)", "dismiss on blur/Esc"],
    a: ["aria-describedby links trigger → tip", "Must also appear on keyboard focus"],
    do: ["Keep under ~8 words", "Trigger on focus too"],
    dn: ["Put essential info only in a tooltip", "Show on click only"] },
  'c-loading': { s: "Spinner & skeleton loading states.",
    p: ["type|spinner · skeleton", "size|sm · md · lg|(md)"],
    t: ["spinner --ys-blue · track --ys-border", "skeleton shimmer --ys-bg-row"],
    st: ["indeterminate (continuous)"],
    a: ["aria-busy on region; aria-live polite for results", "Skeleton hidden from SR (aria-hidden)"],
    do: ["Skeleton for content, spinner for actions", "Reserve final layout space"],
    dn: ["Block the whole screen for small waits", "Spin forever with no timeout"] },
  'c-breadcrumb': { s: "Hierarchical location trail.",
    p: ["items|[{label, href}]", "separator|› (fixed)"],
    t: ["link --ys-blue · current --ys-text", "sep --ys-border-2 · --ys-fs-12"],
    st: ["link hover underline", "current is non-link"],
    a: ["nav + aria-label « fil d'Ariane »", "current has aria-current=page"],
    do: ["Mark the current page non-clickable", "Truncate long middle items"],
    dn: ["Use for steps (use Stepper)", "Exceed one line on mobile"] },
  'c-divider': { s: "Hairline separator, optional label.",
    p: ["orientation|horizontal · vertical|(horizontal)", "label|string (optional)"],
    t: ["colour --ys-border · 1px", "label --ys-muted --ys-fs-12"],
    st: ["Static"],
    a: ["role=separator; decorative dividers aria-hidden"],
    do: ["Use the « ou » label to split form options", "Keep at the border token"],
    dn: ["Use a thick rule", "Separate every row (too noisy)"] },
  /* ── MOLECULES ── */
  'c-card': { s: "Base surface container — the system's atomic unit.",
    p: ["padding|--ys-sp-7/8 (site --ys-sp-10+)", "interactive|boolean|(false)"],
    t: ["bg --ys-white · border --ys-border", "radius --ys-r-lg", "hover border --ys-border-2 + --ys-shadow-sm"],
    st: ["rest (no shadow) → hover (shadow + darker border)"],
    a: ["Whole-card link uses one <a> with a clear label", "Don't nest interactive controls inside a card link"],
    do: ["Keep 10px radius default", "Add shadow only on hover"],
    dn: ["Drop-shadow at rest", "Multiple click targets in a linked card"] },
  'c-selector': { s: "Selectable option card (radio-like group).",
    p: ["selected · disabled|boolean|(false)"],
    t: ["selected border --ys-blue + bg --ys-blue-lt", "radius --ys-r-lg"],
    st: ["default → hover → selected", "focus-visible ring"],
    a: ["radiogroup semantics", "Whole card is the target"],
    do: ["Show a clear selected state", "One choice per group"],
    dn: ["Rely on a tiny check only", "Mix with plain cards"] },
  'c-alert': { s: "Inline contextual message (persists in flow).",
    p: ["tone|info · success · warning · danger|(info)", "dismissible|boolean|(false)"],
    t: ["bg --ys-{tone}-bg · fg --ys-{tone}-fg", "icon --ys-{tone}-fg · radius --ys-r-md"],
    st: ["static; optional dismiss"],
    a: ["role=status (info) / role=alert (danger)", "Icon + text, never colour alone"],
    do: ["Pair an icon with the tone", "Keep it in document flow"],
    dn: ["Use for transient feedback (use Toast)", "Colour-only signalling"] },
  'c-stat': { s: "KPI tile — big numeral + label + trend.",
    p: ["value|string", "label|string", "trend|+/-% (optional)"],
    t: ["value --ys-fs-28/--ys-fw-black", "label --ys-fs-11/--ys-muted", "trend up --ys-success-fg · down --ys-danger-fg"],
    st: ["static"],
    a: ["Trend arrow has text equivalent", "Don't encode meaning in colour only"],
    do: ["One number per tile", "Show the unit/label"],
    dn: ["Stack 3 numbers in one tile", "Tiny KPI numerals"] },
  'c-stepper': { s: "Linear progress through ordered steps.",
    p: ["steps|[label]", "current|index", "orientation|horizontal · vertical"],
    t: ["done --ys-blue · current ring --ys-blue · todo --ys-border-2", "connector --ys-border"],
    st: ["todo → current → done", "error step: --ys-danger-fg"],
    a: ["ol/li; current has aria-current=step", "Announce « étape 2 sur 4 »"],
    do: ["Number the steps", "Show overall position"],
    dn: ["Allow skipping silently", "Use for non-linear nav"] },
  'c-validation': { s: "Form field validation patterns.",
    p: ["state|default · valid · error", "message|string"],
    t: ["valid --ys-success-fg · error --ys-danger-fg", "icon mirrors state"],
    st: ["validate on blur, re-validate on input", "summary on submit"],
    a: ["aria-invalid + aria-describedby", "Move focus to first error on submit"],
    do: ["Validate on blur, not keystroke", "Explain how to fix"],
    dn: ["Validate while typing the first char", "Generic « erreur » with no detail"] },
  'c-formation': { s: "Course product card — image, price, CPF, badge.",
    p: ["layout|grid · list|(grid)", "cpf|boolean", "price · duration · level|string"],
    t: ["radius --ys-r-lg · sector accent per theme", "CPF badge --ys-success-bg/fg"],
    st: ["rest → hover (shadow + lift)"],
    a: ["One link wraps the card title", "Price/CPF are text, not colour-only"],
    do: ["Surface CPF eligibility", "Show duration + level"],
    dn: ["Bury the price", "Multiple competing CTAs"] },
  'c-pricing': { s: "Plan card with feature list & « populaire » variant.",
    p: ["featured|boolean|(false)", "price · period|string", "features|[{label, included}]"],
    t: ["featured border --ys-blue + --ys-shadow-md", "check --ys-success-fg · excluded --ys-border-2"],
    st: ["rest → hover; featured raised"],
    a: ["« populaire » conveyed in text, not colour only", "One CTA per card"],
    do: ["Surface CPF financing", "Highlight one plan"],
    dn: ["Feature more than one plan", "Hide what's excluded"] },
  'c-tabs': { s: "Switch between sibling panels.",
    p: ["tabs|[label]", "active|index", "variant|underline · pill"],
    t: ["active --ys-blue + indicator · idle --ys-muted", "border --ys-border"],
    st: ["idle → hover → active", "focus-visible per tab"],
    a: ["role=tablist/tab/tabpanel", "Arrow-key navigation between tabs"],
    do: ["Keep labels short", "Persist panel content in DOM"],
    dn: ["Use for sequential steps", "More than ~5 tabs on mobile"] },
  'c-toast': { s: "Transient floating snackbar (auto-dismiss).",
    p: ["tone|neutral · success · danger|(neutral)", "duration|ms|(4000)", "action|{label, onAction}"],
    t: ["dark surface --ys-text · fg --ys-white", "radius --ys-r-md · --ys-shadow-lg"],
    st: ["enter (slide/fade) → auto-dismiss → exit", "pause on hover/focus"],
    a: ["aria-live polite (assertive for errors)", "Action reachable by keyboard before dismiss"],
    do: ["Keep to one line + one action", "Auto-dismiss non-critical only"],
    dn: ["Use for content that must persist (use Alert)", "Stack many at once"] },
  'c-pagination': { s: "Navigate paged result sets.",
    p: ["page|index", "total|number", "siblings|count"],
    t: ["current bg --ys-blue · fg white", "idle --ys-text · radius --ys-r-md"],
    st: ["idle → hover → current", "first/last disabled at ends"],
    a: ["nav + aria-label; current aria-current=page", "Prev/next have labels"],
    do: ["Show first/last + ellipsis", "Disable ends correctly"],
    dn: ["Tiny targets", "Hide the current page"] },
  'c-empty': { s: "Empty-state placeholder with guidance + action.",
    p: ["icon · title · description|string", "action|{label}"],
    t: ["muted --ys-muted · icon --ys-border-2", "title --ys-fs-16/--ys-fw-bold"],
    st: ["static"],
    a: ["Decorative icon aria-hidden", "Action is a real button"],
    do: ["Tell the user what to do next", "Keep it calm/encouraging"],
    dn: ["Just say « rien »", "Blame the user"] },
  'c-banner': { s: "Page-level announcement bar, dismissible.",
    p: ["tone|info · brand|(info)", "dismissible|boolean|(true)"],
    t: ["bg --ys-blue-lt / brand · fg --ys-text", "border-bottom --ys-border"],
    st: ["shown → dismissed (persist choice)"],
    a: ["role=region + label", "Dismiss has aria-label; remember dismissal"],
    do: ["One message at a time", "Persist the dismissal"],
    dn: ["Stack with the promo bar", "Re-show every navigation"] },
  'c-dropdown': { s: "Menu of actions/links from a trigger.",
    p: ["align|start · end|(start)", "items|[{label, onSelect}]"],
    t: ["surface --ys-white · border --ys-border", "radius --ys-r-md · --ys-shadow-md"],
    st: ["closed → open; item hover --ys-bg-row", "close on outside/Esc"],
    a: ["role=menu/menuitem; arrow-key nav", "Focus returns to trigger on close"],
    do: ["Group related actions", "Close on select"],
    dn: ["Nest deep submenus", "Put a form inside"] },
  'c-accordion': { s: "Expandable Q&A / disclosure list.",
    p: ["multiple|boolean|(false)", "items|[{q, a}]"],
    t: ["divider --ys-border · chevron --ys-muted", "radius --ys-r-md"],
    st: ["collapsed → expanded (chevron rotates)"],
    a: ["button + aria-expanded + aria-controls", "FAQ uses rich-snippet markup"],
    do: ["Open the first item if useful", "One concise answer each"],
    dn: ["Animate height slowly", "Hide critical content by default"] },
  'c-sector': { s: "Vocational sector card with picto + checklist.",
    p: ["sector|theme key", "items|[label]"],
    t: ["picto + accent per sector theme", "radius --ys-r-lg · check --ys-success-fg"],
    st: ["rest → hover (lift)"],
    a: ["Picto decorative (aria-hidden)", "Card title is the link"],
    do: ["Use the sector's theme colour", "Keep the checklist short"],
    dn: ["Mix sector accents in one card", "Overload with items"] },
  'c-backtotop': { s: "Floating return-to-top button on long pages.",
    p: ["showAfter|px scrolled|(600)"],
    t: ["bg --ys-white · icon --ys-blue", "radius --ys-r-full · --ys-shadow-md"],
    st: ["hidden → fade in past threshold", "hover lift"],
    a: ["aria-label « Revenir en haut »", "Target ≥ 44px; never overlaps sticky CTA"],
    do: ["Appear only after the first fold", "Smooth-scroll to top"],
    dn: ["Cover the sticky mobile CTA", "Show at the top of the page"] },
  /* ── ORGANISMS ── */
  'c-modal': { s: "Focus-trapping overlay dialog.",
    p: ["size|sm · md · lg|(md)", "dismissible|boolean|(true)"],
    t: ["scrim rgba(30,35,60,.4)", "surface --ys-white · radius --ys-r-2xl · --ys-shadow-lg"],
    st: ["pop in (.16s) → open → close", "scrim click / Esc to close"],
    a: ["role=dialog aria-modal; trap focus", "Return focus to opener; label the dialog"],
    do: ["Trap + restore focus", "Close on Esc and scrim"],
    dn: ["Stack modals", "Lose the user's focus position"] },
  'c-table': { s: "Comparison table — desktop grid → mobile swipe/focus.",
    p: ["mode|compare · focus", "columns · rows|data"],
    t: ["header --ys-bg-row · border --ys-border", "radius --ys-r-xl"],
    st: ["desktop full grid", "mobile: swipe columns / focus one"],
    a: ["Real <table> semantics", "Content stays in DOM (no display:none dupes)"],
    do: ["Keep one source of cells", "Pin the row header"],
    dn: ["Duplicate markup per breakpoint", "Hide data with display:none"] },
  'c-datatable': { s: "Record list — rows → expandable cards on mobile.",
    p: ["columns|[field]", "filter|key", "expandable|boolean"],
    t: ["row hover --ys-bg-row · border --ys-border", "radius --ys-r-xl"],
    st: ["desktop rows → mobile accordion cards", "row hover/expand"],
    a: ["<table> + scope headers", "Expand button has aria-expanded"],
    do: ["Expandable card for the long field", "Keep filters visible"],
    dn: ["Nested scroll areas on mobile", "Truncate without a way to read more"] },
  'c-testimonial': { s: "Quote card with author + rating.",
    p: ["compact|boolean|(false)", "rating|0–5"],
    t: ["radius --ys-r-lg · border --ys-border", "stars --ys-orange · avatar --ys-blue-mid"],
    st: ["rest → hover (in a grid)"],
    a: ["blockquote + cite for attribution", "Rating has a text equivalent"],
    do: ["Attribute the quote (name + formation)", "Keep it short"],
    dn: ["Fabricate attribution", "Star colour with no number"] },
  'c-article': { s: "Blog/article body composition.",
    p: ["title · author · date|string", "toc|boolean"],
    t: ["body --ys-fs-13/16 · --ys-lh-base", "links --ys-blue"],
    st: ["static reading view"],
    a: ["One <h1>; ordered heading levels", "Author box supplies E-E-A-T"],
    do: ["Use a sticky ToC on long reads", "Show author + date"],
    dn: ["Skip heading levels", "Walls of text with no rhythm"] },
  'p-grid': { s: "Responsive card-grid section.",
    p: ["columns|2 · 3 · 4|(3)", "gap|--ys-sp-6/9"],
    t: ["gap --ys-sp-6 (app) / larger (site)", "items use Card"],
    st: ["reflows 1→2→3/4 by breakpoint"],
    a: ["Logical source order = visual order", "Each card independently reachable"],
    do: ["Use CSS grid + gap", "Collapse to 1 col on mobile"],
    dn: ["Inline-block float layouts", "Fixed column counts on mobile"] },
  'p-form': { s: "Composed form layout with sections + actions.",
    p: ["layout|single · two-col", "steps|number (optional)"],
    t: ["field gap --ys-sp-7 · section gap --ys-sp-10", "actions pinned bottom"],
    st: ["validate on blur; submit shows summary", "disabled submit until valid (optional)"],
    a: ["Fieldset/legend for groups", "Errors summarised + linked on submit"],
    do: ["Group related fields", "Keep the primary action obvious"],
    dn: ["One giant ungrouped form", "Hide the submit button"] },
  'p-nav': { s: "Header + mega-menu (sticky).",
    p: ["sticky|boolean|(true)", "mega|boolean"],
    t: ["surface --ys-white · border-bottom --ys-border", "height --ys-header-h (50px app)"],
    st: ["rest → sticky shadow on scroll", "mega open on hover/focus"],
    a: ["nav landmark; mega is keyboard-operable", "Current section aria-current"],
    do: ["Keep the primary CTA visible", "Collapse to drawer on mobile"],
    dn: ["Hover-only mega menu", "More than ~6 top items"] },
  'p-footer': { s: "Site footer — columns, legal, newsletter.",
    p: ["columns|link groups", "newsletter|boolean"],
    t: ["bg --ys-text · fg muted-on-dark", "divider rgba(255,255,255,.1)"],
    st: ["static"],
    a: ["contentinfo landmark", "Newsletter input has a label"],
    do: ["Group links logically", "Include legal + certifications"],
    dn: ["Dump every link flat", "Tiny low-contrast text"] },
  'c-drawer': { s: "Mobile slide-in navigation panel.",
    p: ["side|left · right|(left)", "open|boolean"],
    t: ["panel --ys-white · scrim rgba(30,35,60,.4)", "row target ≥ 44px"],
    st: ["closed → slide in + scrim → close", "Esc / scrim / link closes"],
    a: ["role=dialog; trap focus while open", "Return focus to the burger"],
    do: ["44px rows", "Close on navigation"],
    dn: ["Leave background scrollable", "Lose focus on close"] },
  'c-stickycta': { s: "Fixed bottom conversion bar (mobile).",
    p: ["price|string", "action|{label}"],
    t: ["surface --ys-white · --ys-shadow (up)", "primary CTA --ys-blue"],
    st: ["pinned; hides when keyboard open (optional)"],
    a: ["Target ≥ 44px; doesn't trap scroll", "Announce price + action"],
    do: ["One value reminder + one CTA", "Keep it thumb-reachable"],
    dn: ["Overlap Back-to-top", "More than one action"] },
  'c-promo': { s: "Time-boxed promo bar with countdown.",
    p: ["message|string", "deadline|ISO date", "dismissible|boolean|(true)"],
    t: ["bg --ys-text · fg --ys-white", "timer chips --ys-white/--ys-text"],
    st: ["live countdown → expiry hides bar", "dismiss persists"],
    a: ["Countdown via aria-live (polite, throttled)", "Dismiss has a label"],
    do: ["One offer + one timer", "Hide on expiry"],
    dn: ["Stack with the announcement bar", "Per-second aria-live spam"] },
  'c-curriculum': { s: "Course syllabus — module accordion.",
    p: ["modules|[{title, lessons, duration}]", "openFirst|boolean|(true)"],
    t: ["divider --ys-border · index --ys-blue-lt", "chevron --ys-muted"],
    st: ["module collapsed → expanded", "first open by default"],
    a: ["Accordion button + aria-expanded", "Duration/lesson count is text"],
    do: ["Show duration + lesson count", "Open the first module"],
    dn: ["Hide totals", "Force all closed"] },
  'c-toc': { s: "Sticky table of contents for long pages.",
    p: ["items|[{label, anchor}]", "sticky|boolean|(true)"],
    t: ["active rail --ys-blue · idle --ys-muted", "--ys-fs-13"],
    st: ["active section highlighted on scroll", "click scrolls to anchor"],
    a: ["nav + aria-label « sommaire »", "Active link aria-current=true"],
    do: ["Highlight the current section", "Sticky on desktop only"],
    dn: ["Scrollspy that flickers", "Show on small mobile screens"] },
  'c-author': { s: "Author box for E-E-A-T (byline).",
    p: ["name · role · bio|string", "avatar|src/initials"],
    t: ["radius --ys-r-lg · border --ys-border", "avatar --ys-blue-mid"],
    st: ["static"],
    a: ["rel=author link; real name", "Avatar alt / aria-label"],
    do: ["One or two sentence bio", "Establish expertise"],
    dn: ["Fake credentials", "Generic « admin » author"] },
  'c-videomodal': { s: "Lightbox video player from a poster.",
    p: ["poster|src", "src|video url", "title|string"],
    t: ["scrim rgba(30,35,60,.4)", "play button --ys-white · radius --ys-r-2xl"],
    st: ["poster → open lightbox → play", "Esc / scrim closes + pauses"],
    a: ["role=dialog; trap focus", "Captions/transcript available"],
    do: ["Pause on close", "Provide captions"],
    dn: ["Autoplay with sound", "Trap the user with no close"] },
  'pf-components': { s: "Plateforme app-kit components (student/teacher).",
    p: ["context|app surface", "density|compact"],
    t: ["app density --ys-fs-13 base", "--ys-header-h 50 · --ys-sidebar-w 200"],
    st: ["per component (see live app kit)"],
    a: ["French UI throughout", "Status badges use icon + word, not colour only"],
    do: ["Use app density tokens", "Reuse base atoms"],
    dn: ["Marketing-site scale in the app", "Re-invent base components"] },
  /* ── SECTIONS ── */
  'p-feat': { s: "Features grid — icon + title + blurb.",
    p: ["columns|3 · 4|(4)", "items|[{icon, title, text}]"],
    t: ["icon tile --ys-blue-lt · icon --ys-blue", "gap --ys-sp-10"],
    st: ["reflows to 1–2 col on mobile"],
    a: ["Icons decorative (aria-hidden)", "One <h2> for the section"],
    do: ["One line of value per item", "Consistent icon style"],
    dn: ["Paragraphs per feature", "Mismatched icon weights"] },
  'p-pricing': { s: "Pricing section — 2–3 plans compared.",
    p: ["plans|[Pricing card]", "featured|index"],
    t: ["featured raised --ys-shadow-md", "bg --ys-bg"],
    st: ["featured plan highlighted"],
    a: ["Each plan is a labelled group", "« populaire » in text"],
    do: ["Surface CPF everywhere", "Raise one plan"],
    dn: ["More than 3 plans side by side", "Hide exclusions"] },
  'p-stats': { s: "Reassurance stats band.",
    p: ["stats|[{value, label}]", "tone|dark · light|(dark)"],
    t: ["value --ys-fs-28/black", "bg --ys-text (dark band)"],
    st: ["static (optional count-up)"],
    a: ["Each stat reads value + label", "Count-up respects reduced-motion"],
    do: ["Round, memorable numbers", "Label every figure"],
    dn: ["Unsourced claims", "Six stats in a row"] },
  'p-testimonials': { s: "Testimonials section with headline.",
    p: ["quotes|[Testimonial]", "headline · rating|string"],
    t: ["grid gap --ys-sp-6", "stars --ys-orange"],
    st: ["grid reflows on mobile"],
    a: ["Real attributions", "Rating text equivalent"],
    do: ["Show the aggregate rating + count", "Attribute each quote"],
    dn: ["Anonymous fabricated quotes", "Star-only ratings"] },
  'p-cta': { s: "Full-width call-to-action band.",
    p: ["headline · subtext|string", "action|{label}"],
    t: ["brand fill · fg --ys-white", "CTA --ys-white on brand"],
    st: ["static"],
    a: ["One <h2> + one primary action", "Contrast AA on the band"],
    do: ["One headline, one CTA", "Add a reassurance line"],
    dn: ["Multiple CTAs", "Low-contrast text on the fill"] },
  'p-trust': { s: "Certifications / partner marks band.",
    p: ["marks|[logo]", "title|string"],
    t: ["mark tile --ys-bg · border --ys-border", "label --ys-muted"],
    st: ["static (optional marquee)"],
    a: ["Each logo has alt text", "Marquee pauses on hover/focus"],
    do: ["Use official assets in prod", "Keep marks monochrome if noisy"],
    dn: ["Placeholder logos in production", "Auto-scroll with no pause"] },
  'p-newsletter': { s: "Email capture band.",
    p: ["placeholder|string", "consent|boolean copy"],
    t: ["input --ys-white · CTA --ys-blue", "consent --ys-muted --ys-fs-11"],
    st: ["default → success confirmation"],
    a: ["Input has a label", "Consent text + link to privacy"],
    do: ["Single field + button", "State frequency (« un email / mois »)"],
    dn: ["Ask for more than the email", "Hide the consent notice"] },
  /* ── TEMPLATES (beta) ── */
  'p-header': { s: "Page header band template.",
    p: ["title · breadcrumb|string", "actions|[Button]"],
    t: ["bg --ys-white/brand · --ys-content-max", "title --ys-fs-20/black"],
    st: ["static"],
    a: ["One <h1>; breadcrumb is nav", "Actions are real buttons"],
    do: ["One clear page title", "Keep actions to ≤ 2"],
    dn: ["Multiple H1s", "Crowd the header"] },
  'p-lead': { s: "Lead-capture form template.",
    p: ["fields|[Input]", "reassurance|column"],
    t: ["card --ys-r-lg · CTA --ys-blue", "reassurance --ys-success-fg checks"],
    st: ["validate on blur → submit → success"],
    a: ["Labels + error summary", "Phone/email correct input types"],
    do: ["Pair the form with reassurance", "Ask only what you need"],
    dn: ["Long forms with no rationale", "No success confirmation"] },
  'p-home': { s: "Home page composition (beta).",
    p: ["sections|Header→Hero→Features→Formations→Trust→CTA→Footer"],
    t: ["section rhythm --ys-sp-12+", "--ys-content-max 1500"],
    st: ["static page assembly"],
    a: ["Logical heading order", "One H1 (hero)"],
    do: ["Lead with the hero value + CTA", "Reassure (CPF, Trust) early"],
    dn: ["Multiple H1s", "Bury the primary CTA"] },
  'p-formation': { s: "Course (formation) page (beta).",
    p: ["hero|price/CPF", "programme|Curriculum", "stickyCta|boolean"],
    t: ["price card --ys-shadow", "CPF --ys-success-bg/fg"],
    st: ["sticky CTA on mobile"],
    a: ["Breadcrumb + one H1", "Programme is an accordion"],
    do: ["Surface price + CPF above the fold", "Sticky CTA on mobile"],
    dn: ["Hide the price", "No clear enrol action"] },
  'p-categorie': { s: "Category listing page (beta).",
    p: ["filters|[Tag]", "grid|Formation cards"],
    t: ["filter chips --ys-blue-mid selected", "grid gap --ys-sp-6"],
    st: ["filter narrows the grid"],
    a: ["Filters are checkboxes/buttons", "Result count announced"],
    do: ["Show result count", "Keep filters visible"],
    dn: ["Filter without feedback", "Lose scroll position on filter"] },
  'p-blog': { s: "Blog index / article list (beta).",
    p: ["posts|[Blog card]", "categories|[Tag]"],
    t: ["card --ys-r-lg", "category --ys-blue-fg"],
    st: ["grid reflow; optional pagination"],
    a: ["Each card title is the link", "One H1 for the index"],
    do: ["Show date + category", "Consistent card heights"],
    dn: ["Endless scroll with no anchor", "Mismatched excerpts"] },
  'p-article': { s: "Single article page (beta).",
    p: ["title · author|string", "toc|boolean", "authorBox|boolean"],
    t: ["body --ys-lh-base", "ToC active rail --ys-blue"],
    st: ["sticky ToC; scrollspy"],
    a: ["One H1; ordered headings", "Author box for E-E-A-T"],
    do: ["Sticky ToC on desktop", "Show author + date"],
    dn: ["Skip heading levels", "No author attribution"] },
  'p-contact': { s: "Contact / lead page (beta).",
    p: ["form|Lead", "reassurance|column"],
    t: ["card --ys-r-lg · CTA --ys-blue", "reassurance checks --ys-success-fg"],
    st: ["validate → submit → confirmation"],
    a: ["Correct input types; labels", "Confirmation announced"],
    do: ["Offer a callback option", "Set expectations (« sous 24 h »)"],
    dn: ["Only an email address", "No confirmation state"] }
};
