name: Deploy to apollo.youschool.fr

on:
  push:
    branches:
      - main
      - stable

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          known_hosts: "72.60.47.231 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDYXgYzkvL4py0tX3wEtU8kSqk8qoXuVtoVkEZJ/K4VF"
          script: |
            cd /home/youschool-apollo/htdocs/apollo.youschool.fr
            git pull origin stable
