name: Deploy to apollo.youschool.fr

on:
  push:
    branches:
      - main
      - stable

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          use_insecure_cipher: true
          script: |
            cd /home/youschool-apollo/htdocs/apollo.youschool.fr
            git fetch origin stable
            git reset --hard origin/stable
